MichaelEbert/OblivionProgressTracker

- glitches.html
#9 
Added 8 potion glitch section (8 skooma glitch)
"cleaning"
- added indents within sections and lists
- put numbered items into OLs,
- expanded and organized Table of contents
> Cleaned glitches, added 8 Skooma/potion Glitch

- autoread.js
- speedrun-3.html
Small change to fix #35  (not sure why I even bothered raising an issue for it)
> Make "Enable Speech" button disabled after being clicked

- autoread.js
#16 
added playHotKey
added 2 listeners
1.  keydown
2.  touchstart
keydown filters to the spacebar to progress the SB
also added scrolling so that the page tracks w/ what SB is reading.
> SpeechBox Hotkey

- casual.html
- data/book.json
- data/misc.json
- data/quest.json
- data/save.json
- data/store.json
- index.html
- injection.js
- main.js
- progress.js
- speedrun-3.html
Refactoring:
- Moved json data functions from progress.js to obliviondata.js.
- Changed terminology. Call the root of the oblivion data json trees 'hives', and the individual leaf nodes 'cells', to better differentiate between when we're talking about hives, generic 'nodes' in recursive functions, and specifically 'cell' leaf nodes.
- Moved save compression into their own functions, will be useful for save sharing.
- Consolidated speedrun-3 init functions into init() in injection.js.
- Moved progression weight into individual hive files for v2+, to match misc.json.
- renamed saveProgress to saveProgressToCookie to match loadProgressFromCookie
Cleanup
- rewrote classes class. Now includes "shouldSave" field, used in many functions. classes that contain data that should be saved are called …
> Major refactor and cleanup of code.

- casual.html
- data/book.json
- data/minipages/book/book.html
- data/minipages/npc/npc.html
- data/misc.json
- data/quest.json
- data/save.json
- data/store.json
- index.html
- injection.js
- main.js
- obliviondata.js
- progress.js
- settings.html
- speedrun-3.html
Added in obliviondata.js, so this should now work.
Major refactor and cleanup of code.
Refactoring:
- Moved json data functions from progress.js to obliviondata.js.
- Changed terminology. Call the root of the oblivion data json trees 'hives', and the individual leaf nodes 'cells', to better differentiate between when we're talking about hives, generic 'nodes' in recursive functions, and specifically 'cell' leaf nodes.
- Moved save compression into their own functions, will be useful for save sharing.
- Consolidated speedrun-3 init functions into init() in injection.js.
- Moved progression weight into individual hive files for v2+, to match misc.json.
- renamed saveProgress to saveProgressToCookie to match loadProgressFromCookie
Cleanup
- rewrote classes class. Now includes "shouldSave" …
> Module refactor

- autoread.js
now handles sub lists. both unordered and ordered.
also moved the auto scrolling line to appropriate function/area.
this resolves #43 and #17
> Added Speechbox sublist handling.

- casual.html
- data/misc.json
- glitches.html
- index.html
- injection.js
- main.css
- main.js
- obliviondata.js
- speedrun-3.html
- Made images clickable and open in iframe. not super useful because they're already right there but whatever.
- removed commented code. Added spacers to top links. Added full top links to glitches page.
- added extra column capability to json. fixes #7
- slightly updated function doc to jsdoc
- added parent property to hive data
> Miscellaneous fixes

- main.css
- speedrun-3.html
Added arena content to guide w/ formatting
let me know if you see typos etc...
also minor cleanup on speedrun guide, removed some double IDs on some sections and made whitespace more uniform when i noticed it.
> Added Arena Content to Guide

- speedrun-3.html
> Added Sidequest content

- injection.js
- sharing.js
fixed issue when you try to load a share and dont have a progress_local
> Better speedrun error message; fixed issue with sharing

- data/quest.json
- map.html
- map.js
Moved majority of UI code/functionality to be in HTML rather than JavaScript.
resolves #118
> UI Migration from map.js to map.html

- map.js
- map/mapObject.mjs
Very smart way to integrate on hover text items, very easy to add to.
> Added travel time calculation to mapobject.mjs.

- casual.html
- data/location.json
- data/misc.json
- data/nirnroot.json
- glitches.html
- index.html
- map.html
- progress.js
- readme.md
- settings.html
- speedrun-3.html
moved settings to the last page in the topbar. Added link to prclive wiki for glitches.
added 4 journal-filled quests to quest subtotal so it doesn't confuse people
added max property for intermediate json nodes
moved locations and nirnroot sums to their own files instead of in the misc file
> Formatting

- tools/spellstacking.html
- tools/spellstacking.js
Here's the spell stacking calculator.
I don't do web development much, so let me know if there are any stylistic things that should be changed.
> Add spell stacking calculator

- data/misc.json
- data/nirnroot_custom.json
- guide.js
- js/common.mjs
- js/map.mjs
- js/map/mapObject.mjs
- js/map/overlay.mjs
- js/map/point.mjs
- js/nirnroute.mjs
- js/progress.mjs
- js/userdata.mjs
- main.css
- main.js
- map.html
- nirnroute.html
- readme.md
Added closed gates to progress.
You can now double click on a discovered gate to mark it as closed.
You can now scroll the map on touch.
Switched from cookies to localStorage.
Significant performance optimizations.
Added nirn fact and instructions to nirnroot pages.
> Oblivion gate closures and other stuff

- data/misc.json
- data/misc_custom.json
- data/quest.json
- index.html
- js/userdata.mjs
- readme.md
- settings.html
- settings.js
Fixes so the save reader can work
> Save reader fixes

- data/minipages/book/book.html
- data/minipages/book/bookpage.js
- index.html
- js/cellGenerator.mjs
- js/map.mjs
- js/map/mapObject.mjs
- js/map/overlay.mjs
- js/nirnroute.mjs
- js/obliviondata.mjs
- js/progress.mjs
- js/sharing.mjs
- js/userdata.mjs
- main.js
- map.html
- nirnroute.html
- server/ProgressManagerSql.cs
- server/db.sql
- server/user.sql
- settings.html
- settings.js
- speedrun-3.html
Fixed bug where clicking on 'prev' on 0th nirnroot would cause 'next' button to not work
Updated obliviondata.js to be a module (probably broke loads of stuff)
Fixed bug where sharing for the first time wouldn't update URL
Added reset button to settings page. Fixed reset button on main page.
Server schema changes
> Misc fixes

- js/map/overlay.mjs
- js/map/tspPath.mjs
- map.html
> Map and rendering fixes

- guide.js
- js/cellGenerator.mjs
- js/obliviondata.mjs
- js/sharing.mjs
- main.js
- map.html
> separate map links

- guide.css
- main.html
Fixes small issues resulting from conflicts in the other PR.
> Quick fix (hopefully)

- index.html
- speedrun-guide.html
redirecting using the meta tag doesn't seem to work when the whole site is under a subdirectory since it removes it from the url, so I switched to a js solution.
> Urgent: fixed redirect pages so site doesn't 404 immediately

- checklist-template.html
- checklist.html
- contributing.md
- data/minipages/book/book.html
- js/obliviondata.mjs
- js/sharing.mjs
- nirnroute.html
Updated debugging information to use debug object instead of debug true/false.
Fixed bug where page would not attach spectate updater if first update returned 304 unchanged. Fixed bug where save uploader would only work on settings page.
> sharing bugfixes

- js/map.mjs
- js/userdata.mjs
- map.html
- server/ProgressManagerSql.cs
- speedrun-4.html
-  added gate toggle, fixing #347
- made [gate], [npc] etc hidden by default
- fixed issue with mages guild save being disabled
- added in some suprise code that will help us later ;)
> Minor fixes.

- js/settings.mjs
- js/sharing.mjs
- js/userdata.mjs
- nirnroute.html
- server/Controllers/KeySyncController.cs
- server/ProgressManagerSql.cs
- settings.html
Add the ability to easily sync writes between the website and the app, or the website and another device.
> Add write sync
